version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  aioz-ads-db:
    image: postgres:16-alpine
    container_name: aioz-ads-db
    env_file:
      - ./app.env
    ports:
      - "5438:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

  aioz-ads:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aioz-ads
    ports:
      - "8084:8080"
    env_file:
      - ./app.env
    networks:
      - app-network
    depends_on:
      - aioz-ads-db
      - aioz-ads-redis

  aioz-ads-redis:
    image: redis:7.4.1
    container_name: aioz-ads-redis
    ports:
      - "6379:6379"
    env_file:
      - ./app.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:
    driver: local
  postgres_data_dev:
    driver: local
  clickhouse_data:
    driver: local
