basePath: /api/v1
definitions:
  handlers.CreateUserRequest:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      deleted_at:
        type: string
      deleted_by:
        type: string
      display_email:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      status:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
      username:
        type: string
    type: object
  response.GeneralResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: AIOZ ADS SERVICE API DOCUMENTATION
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AIOZ ADS SERVICE
  version: "1.0"
paths:
  /auth/sign-up:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: sign up new user
      parameters:
      - description: create org input
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GeneralResponse'
      summary: Sign up
      tags:
      - auth
  /user/me:
    get:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.GeneralResponse'
      security:
      - BasicAuth: []
      - Bearer: []
      summary: Get me
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
